### ISSUE TITLE
question: where the crds should be? on addons or workloads

### ISSUE THREAD

**Issue by flavono123** [gitops-bridge-dev/gitops-bridge#43]
e.g. for karpanter, where provisioners or node templates should be at addons or workloads?
in workloads, implement is simple i think but how or possible to be in addons?

**Comment by flavono123** [comment]
one solution could be a value like `extraObjects` in addon(chart); (grafana, ...):
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L1290

but not for others(karpenter):
https://github.com/aws/karpenter-provider-aws/pull/3803

> Since Helm offers no in-chart dependency mechanisms (beyond hooks, which do not work in this case), the Karpenter maintainer team recommends that, if you want to install Karpenter manifests as a helm chart (alongside Karpenter), it should be done using a separate chart that can take the aws/karpenter chart as a dependency so there is a strict ordering for install.

in this point, crds(or resources not in chart) from addon should be in workloads

**Comment by csantanapr** [comment]
I would consider the karpenter controller and CRD, webhooks as addons/plugins for the cluster, this is something that get's install by the team that is vending the cluster.

The CRs, like Karpenter NodePoll and NodeClass are workloads related, I would make them part of workloads.
