### ISSUE TITLE
karpenter pattern

### ISSUE THREAD

**Issue by csantanapr** [gitops-bridge-dev/gitops-bridge#45]
Create pattern running karpenter

Maybe try to see if we can run controllers on fargate/serverless (ie coredns, argocd, alb, karpenter)

**Comment by csantanapr** [comment]
Depends on https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/issues/34

**Comment by mbuotidem** [comment]
Is this handled by https://github.com/gitops-bridge-dev/gitops-bridge/pull/50 ?

**Comment by csantanapr** [comment]
Yes @mbuotidem !
Closing
