### ISSUE TITLE
private repos example - wrong ssh url , will cause "invalid auth method" in argo

### ISSUE THREAD

**Issue by corganfuzz** [gitops-bridge-dev/gitops-bridge#65]
in the [docs](https://github.com/gitops-bridge-dev/gitops-bridge/blob/main/argocd/iac/terraform/examples/eks/private-git/README.md) for private repos, it says:

```bash
export TF_VAR_gitops_addons_org=https://github.com/YOUR_PRIVATE_ORG
```
this is wrong and it will cause an error in argo authorization a message like `invalid auth method`

once I switch to:

```bash
export TF_VAR_gitops_addons_org="git@github.com:YOUR_RPIVATE_ORG"
```
everything worked as intended

**Comment by csantanapr** [comment]
Good catch!

**Comment by csantanapr** [comment]
This is fixed now https://github.com/gitops-bridge-dev/gitops-bridge/commit/66bde3ec1d3ed50248ba4d25b8979141837be01a#diff-cd56d1601d701d555c3cd235559995585d9f00362ff0f7256d048dd1f9ba3b73
